name: Example Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 22f1001551@ds.study.iitm.ac.in
        run: echo "Hello, world!"
